Repository WordPress/wporg-theme-directory, pull requests merged in 2024-06, with the labels that each got.

#107 Favorite button: Add visible text to button
  source/wp-content/themes/wporg-themes-2024/functions.php
  source/wp-content/themes/wporg-themes-2024/patterns/single.php
  source/wp-content/themes/wporg-themes-2024/src/favorite-button/render.php
  source/wp-content/themes/wporg-themes-2024/src/favorite-button/style.scss
  source/wp-content/themes/wporg-themes-2024/src/favorite-button/view.js
Labels: [Component] Blocks

#116 SEO/Social meta: First pass to add meta and opengraph tags
  source/wp-content/themes/wporg-themes-2024/functions.php
  source/wp-content/themes/wporg-themes-2024/inc/block-config.php
  source/wp-content/themes/wporg-themes-2024/inc/seo-social-meta.php
Labels: [Component] Backend

#111 Move see all review link under the ratings.
  source/wp-content/themes/wporg-themes-2024/inc/block-bindings.php
  source/wp-content/themes/wporg-themes-2024/patterns/single.php
Labels: [Status] Needs Design Feedback

#126 Theme previewer: Use listbox for theme patterns & style variation lists to improve selection UX
  source/wp-content/themes/wporg-themes-2024/src/style/_listbox.scss
  source/wp-content/themes/wporg-themes-2024/src/style/style.scss
  source/wp-content/themes/wporg-themes-2024/src/theme-patterns/block.json
  source/wp-content/themes/wporg-themes-2024/src/theme-patterns/index.php
  source/wp-content/themes/wporg-themes-2024/src/theme-patterns/render.php
  source/wp-content/themes/wporg-themes-2024/src/theme-patterns/style.scss
  source/wp-content/themes/wporg-themes-2024/src/theme-patterns/view.js
  source/wp-content/themes/wporg-themes-2024/src/theme-previewer/_page.scss
  source/wp-content/themes/wporg-themes-2024/src/theme-previewer/iframe/render.php
  source/wp-content/themes/wporg-themes-2024/src/theme-previewer/index.js
  source/wp-content/themes/wporg-themes-2024/src/theme-previewer/render.php
  source/wp-content/themes/wporg-themes-2024/src/theme-previewer/view.js
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations-items/block.json
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations-items/index.php
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations-items/render.php
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations-items/view.js
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations/index.php
  source/wp-content/themes/wporg-themes-2024/src/theme-style-variations/style.scss
  source/wp-content/themes/wporg-themes-2024/src/utils/listbox.js
Labels: [Component] Preview
